GET http://localhost:5001/guard

###

GET http://localhost:5001/schedule

###

GET http://localhost:5001/contract

###

POST http://localhost:5001/guard
Content-Type: application/json

{
    "name": "Dhruv",
    "hasArmedGuardCredential": false,
}

###

POST http://localhost:5001/guard
Content-Type: application/json

{
    "name": "Deb",
    "hasArmedGuardCredential": true
}

###

//delete Dhruv
DELETE http://localhost:5001/guard/64692f7fb024c24c281542d4

###

//delete contract
DELETE http://localhost:5001/contract/646a56a2035f193d164f725b

###

PATCH http://localhost:5001/guard/64692f37b024c24c281542ce
Content-Type: application/json

{
    "daysOccupied": [],
    "hoursWorked": 0
}

###

PATCH http://localhost:5001/guard/64692f7fb024c24c281542d4
Content-Type: application/json

{
    "pto": "Thursday"
}

###

PATCH http://localhost:5001/contract/64693561b024c24c281542db
Content-Type: application/json

{
    "name": "TheRitz",
    "requiresArmedGuardCredential": true,
    "daysOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday"]
}

###

POST http://localhost:5001/contract
Content-Type: application/json

{
    "name": "TheRitz",
    "requiresArmedGuardCredential": true,
    "daysOfWeek": ["Monday", "Tuesday"]
}

###

DELETE http://localhost:5001/contract/

###

DELETE http://localhost:5001/schedule/

###

POST http://localhost:5001/contract
Content-Type: application/json

{
    "name": "Hilton",
    "requiresArmedGuardCredential": true,
    "daysOfWeek": ["Wednesday", "Thursday", "Friday"]
}

###

POST http://localhost:5001/contract
Content-Type: application/json

{
    "name": "Sheraton",
    "requiresArmedGuardCredential": false,
    "daysOfWeek": ["Monday", "Tuesday"]
}