GET http://localhost:5001/guard

###

GET http://localhost:5001/schedule

###

GET http://localhost:5001/schedule?start=05/28/2023&end=06/15/2023

###

GET http://localhost:5001/contract

###

POST http://localhost:5001/guard
Content-Type: application/json

{
    "name": "Dhruv",
    "hasArmedGuardCredential": true
}

###

//delete Dhruv
DELETE http://localhost:5001/guard/646af52b025b97c987a0f737

###

//delete contract
DELETE http://localhost:5001/contract/646af67d40a69479e8c8c9e1

###

PATCH http://localhost:5001/guard/646af52b025b97c987a0f737
Content-Type: application/json

{
    "daysOccupied": [],
    "hoursWorked": 0
}

###

PATCH http://localhost:5001/guard/646af52b025b97c987a0f737
Content-Type: application/json

{
    "pto": "05/23/2023"
}

###

PATCH http://localhost:5001/contract/64693561b024c24c281542db
Content-Type: application/json

{
    "name": "TheRitz",
    "requiresArmedGuardCredential": true,
    "daysOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday"]
}

###

POST http://localhost:5001/contract
Content-Type: application/json

{
    "name": "TheRitz",
    "requiresArmedGuardCredential": true,
    "daysOfWeek": ["Monday", "Tuesday"]
}

###

DELETE http://localhost:5001/contract/

###

DELETE http://localhost:5001/schedule/

###

POST http://localhost:5001/contract
Content-Type: application/json

{
    "name": "Hilton",
    "requiresArmedGuardCredential": true,
    "daysOfWeek": ["Wednesday", "Thursday", "Friday"]
}

###

POST http://localhost:5001/contract
Content-Type: application/json

{
    "name": "Sheraton",
    "requiresArmedGuardCredential": false,
    "daysOfWeek": ["Monday", "Tuesday"]
}